apiVersion: batch/v1
kind: Job
metadata:
  name: one
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["/bin/sh", "-c", "echo Job 1; sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: two
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["/bin/sh", "-c", "echo Job 2; sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: three
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["/bin/sh", "-c", "echo Job 3; sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: four
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["/bin/sh", "-c", "echo Job 4; sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: five
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["/bin/sh", "-c", "echo Job 5; sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: six
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["/bin/sh", "-c", "echo Job 6; sleep 5"]
      restartPolicy: Never
